config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end
  resources :users, only: [:show]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :events

  resources :attendances, only: [:create, :destroy]

  resources :invites, only: [:create, :destroy]
  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :attendee, class_name: "User", foreign_key: "attendee_id"
    belongs_to :attended_event, class_name: "Event", foreign_key: "attended_event_id"
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :host, class_name: "User", foreign_key: "host_id"

    has_many :attendances, foreign_key: "attended_event_id", dependent: :destroy
    has_many :attendees, through: :attendances

    has_many :invites, inverse_of: :event

    validates :name, presence: true
    validates :description, presence: true
    validates :location, presence: true
    validate :date_must_be_valid

    scope :past, -> { where('date < ?', DateTime.now) }
    scope :upcoming, -> { where(date: DateTime.now..) }

    def date_must_be_valid
        if date < DateTime.now
            errors.add(:date, "must be valid")
        end
    end
end

app/models/invite.rb
class Invite < ApplicationRecord
    belongs_to :invited, class_name: "User", inverse_of: :invites_received
    belongs_to :inviting, class_name: "User", inverse_of: :invites
    belongs_to :event, inverse_of: :invites
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable    
  
  has_many :events, foreign_key: "host_id", dependent: :destroy

  has_many :attendances, foreign_key: "attendee_id", dependent: :destroy
  has_many :attended_events, through: :attendances

  has_many :invites, foreign_key: "inviting_id", 
    inverse_of: :inviting, dependent: :destroy
  has_many :invited, through: :invites

  has_many :invites_received, foreign_key: "invited_id",
            class_name: "Invite", inverse_of: :invited, dependent: :destroy
  has_many :inviting, through: :invites_sent

  validates :name, presence: true
  validates :password, presence: true
  validates :email, presence: true

  scope :all_except, ->(user_id) { where.not(id: user_id) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_paramaters, if: :devise_controller?

    protected

    def configure_permitted_paramaters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
    end

    private

    def require_login
        unless signed_in?
            flash[:error] = "You must be logged in to do this action"
            redirect_to new_user_session_path
        end
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
    before_action :require_login, only: [:create]

    def create
        @attendance = current_user.attendances.create(attended_event_id: params[:event_id])
        invite = current_user.invites_received.find_by(event_id: params[:event_id])

        invite.destroy

        flash[:success] = "Successfully accepted Invite."
        redirect_to event_path(params[:event_id])
    end

    def destroy
        @attendance = current_user.attendances.find_by(attended_event_id: params[:event_id])

        @attendance.destroy

        flash[:success] = "Successfully cancelled Attendance."
        redirect_to event_path(params[:event_id]), status: 303
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login, only: [:new]

    def index
        @events = Event.all
    end

    def show
        @event = Event.find(params[:id])
        @users = User.all_except(current_user) - @event.attendees
    end

    def new
        @event = Event.new
    end

    def create
        @event = current_user.events.build(event_params)

        if @event.save
            flash[:success] = "Successfully created Event."
            redirect_to @event
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @event = Event.find(params[:id])
    end

    def update
        @event = Event.find(params[:id])

        if @event.update(event_params)
            flash[:success] = "Successfully updated Event."
            redirect_to @event
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @event = Event.find(params[:id])

        @event.destroy

        flash[:success] = "Successfully deleted Event."
        redirect_to root_path, status: 303
    end

    private
    def event_params
        params.require(:event).permit(:name, :description, :date, :location, :host_id)
    end
end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    def create
        event_host = Event.find(params[:event_id]).host
        @invite = event_host.invites.create(event_id: params[:event_id], invited_id: params[:invited_id])

        redirect_to event_path(params[:event_id])
    end

    def destroy
        event_host = Event.find(params[:event_id]).host
        @invite = event_host.invites.find_by(event_id: params[:event_id], invited_id: params[:invited_id])

        @invite.destroy
        redirect_to event_path(params[:event_id]), status: 303
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invites_helper.rb
module InvitesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_attendees.html.erb
<div class="attendees">
    <h2>Current Attendees (<%= attendees.count %>) </h2>
    <% if attendees.empty? %>
        <p class="text-muted">No attendees yet!</p>
    <% end %>
    <div class="list-group">
        <% attendees.each do |attendee| %>
            <%= link_to attendee.name, attendee, class: "list-group-item"%>
        <% end %>
    </div>
</div>

app/views/events/_event.html.erb
<div class="event-card card m-5 <%= "w-25" if (controller.controller_name == "events"  && controller.action_name == "index") || (controller.controller_name == "users"  && controller.action_name == "show") %> ">

    <h3 class="card-header text-center"> <%= link_to event.name, event, class: "text-decoration-none" %> </h3>
    <div class="card-body">
        <p class="card-text <%= "text-truncate" if (controller.controller_name == "events"  && controller.action_name == "index") || (controller.controller_name == "users"  && controller.action_name == "show") %> "> <%= event.description %> </p>
    </div>

    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <p class="text-muted">Location</p>
            <h5 class="m-3"> <%= event.location %> </h5>
        </li>
        <li class="list-group-item">
            <p class="text-muted">Date</p>
            <h5 class="m-3"> <%= event.date %> </h5>
        </li>
        <li class="list-group-item">
            <p class="text-muted">Host</p>
            <h5 class="m-3"> <%= link_to event.host.name, event.host, class: "text-decoration-none" %> </h5>
        </li>
    </ul>

    <% if controller.controller_name == "events" && controller.action_name == "show" %>
        <div class="card-body">
            <%= render "event_buttons", event: event %>
        </div>
    <% end %>
</div>

app/views/events/_event_buttons.html.erb
<div class="event-buttons">
    <% if current_user == event.host %>
        <div class="host-buttons m-3 d-flex justify-content-center">
            <% if event.date < DateTime.now %>
                <%= button_to "Delete Event", event_path, :method => :delete, class: "btn btn-warning m-1" %>
            <% else %>
                <%= button_to "Delete Event", event_path, :method => :delete, class: "btn btn-warning m-1" %>
                <%= link_to "Edit Event Details", edit_event_path, class: "btn btn-secondary m-1" %>
            <% end %>
        </div>
    <% else %>
        <div class="attendance-button">
            <% if event.date < DateTime.now %>
                <p class="text-muted text-center">This event has expired.</p>
            <% elsif current_user != nil && current_user.attended_events.include?(event) %>
                <%= button_to "Cancel Attendance", attendance_path(event_id: event.id), :method => :delete, class: "btn btn-dark w-25" %>
            <% elsif current_user != nil && current_user.invites_received.any? { |invite| invite.event_id == event.id} %>
                <div class="d-flex justify-content-center">
                    <%= button_to "Accept Invite (Attend)", attendances_path(event_id: event.id), :method => :post, class: "btn btn-dark m-2" %>
                    <%= button_to "Ignore Invite", invite_path(event_id: event.id, invited_id: current_user.id), :method => :delete, class: "btn btn-danger m-2" %>
                </div>
            <% elsif current_user == nil%>
                <p class="text-muted text-center"><%= link_to "Sign in", new_user_session_path, class:"text-decoration-none" %> to interact with this event</p>
            <% else %>
                <p class="text-muted text-center">You need to be invited to interact with this event</p>
            <% end %>
        </div>
    <% end %>
</div>

app/views/events/_events.html.erb
<% unless events.empty? %>
    <div class="container-fluid d-flex flex-wrap justify-content-center">
        <% events.each do |event| %>
            <%= render "events/event", event: event %>
        <% end %>
    </div>
<% else %>
    <p class="text-muted text-center">None.</p>
<% end %>

app/views/events/_form.html.erb
<%= form_with model: event do |form| %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control mb-3" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control mb-3" %>
  </div>

  <div class="form-group">
    <%= form.label :location %>
    <%= form.text_field :location, class: "form-control mb-3" %>
  </div>

  <div class="form-group">
    <%= form.label :date %><br>
    <%= form.datetime_select :date, class: "form-control mb-4" %>
  </div>

  <% if event.errors.any? %>
    <div class="errors">
      <% event.errors.full_messages.each do |message| %>
        <p class="text-warning mt-3 p-2"><%= message %></p>
      <% end %>
    </div>
  <% end %>

  <%= form.button button_text, type: "submit", :class=> "mt-3 btn btn-primary" %>
<% end %>

app/views/events/_invite_users_tab.html.erb
<div class="d-flex justify-content-center">
    <div class="invite-users-tab card mb-5 w-50">
        <h4 class="card-header text-center">Manage invitations</h4>
    
        <% if users.empty? %>
            <p class="text-muted text-center mt-1">No users to invite!</p>
        <% else %>
            <ul class="list-group list-group-flush">
                <% users.each do |user| %>
                    <li class="list-group-item d-flex justify-content-between align-items-center <%= @event.invites.find_by(event_id: event.id, invited_id: user.id) ? "order-1" : "order-2" %> ">
                        <div class="text-truncate"> <%= link_to user.name, user, class: "text-decoration-none" %> </div>
                        <% if @event.invites.find_by(event_id: event.id, invited_id: user.id) %>
                            <%= button_to "Cancel Invite", invite_path(event_id: event.id, invited_id: user.id), :method => :delete, class: "btn btn-danger btn-sm ms-1" %>
                        <% else %>
                            <%= button_to "Invite", invites_path(event_id: event.id, invited_id: user.id), :method => :post, class: "btn btn-success btn-sm ms-1" %>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        <% end %>
    </div>
</div>

app/views/events/_invitees.html.erb
<div class="invitees">
    <h2>Currently Invited (<%= invites.count %>) </h2>
    <% if invites.empty? %>
        <p class="text-muted">No invites yet!</p>
    <% end %>

    <div class="list-group">
        <% invites.each do |invite| %>
            <%= link_to invite.invited.name, invite.invited, class: "list-group-item"%>
        <% end %>
    </div>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event, button_text: "Update Event" %>

app/views/events/index.html.erb
<h1>Homepage</h1>
<% unless @events.empty? %>
    <div class="homepage-links text-center">
        <a href="#upcoming_events" class="btn btn-secondary m-1">Upcoming Events</a>
        <a href="#past_events" class="btn btn-secondary m-1">Past Events</a>
    </div>

    <div class="upcoming-events">
        <h1 class="text-center m-4" id="upcoming_events">Upcoming Events</h1>
        <%= render "events", events: @events.upcoming %>
    </div>
    <hr>
    <div class="past-events">
        <h1 class="text-center m-4" id="past_events">Past Events</h1>
        <%= render "events", events: @events.past %>
    </div>
<% else %>
    <p class="text-muted text-center">Any created events will be available here.</p>
<% end %>

app/views/events/new.html.erb
<h1>Create Event</h1>

<%= render "form", event: @event, button_text: "Create Event" %>

app/views/events/show.html.erb
<h1>Event <%= @event.id %></h1>

<% if current_user == @event.host && @event.date >= DateTime.now %>
    <%= render "event", event: @event %>
    <%= render "invite_users_tab", users: @users, event: @event %>
<% else %>
    <%= render "event", event: @event %>
<% end %>

<% unless @event.date < DateTime.now %>
    <div class="event-users d-flex justify-content-evenly">
        <%= render "attendees", attendees: @event.attendees %>
        <%= render "invitees", invites: @event.invites %>
    </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Private Events - Privateers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% unless flash.empty? %>
      <div class="flash-container bg-light border">
        <% flash.each do |type, msg| %>
          <div class="flash">
            <p class="text-muted"><%= type.capitalize %></p>
            <h6><%= msg %></h6>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="wrapper m-3 me-0">
      <aside class="ps-3 pe-3 border-end">
        <h1>Privateers</h1>
        <nav class="nav flex-column">
          <%= link_to "Homepage", root_path, class: "nav-link" %>
          <%= link_to "Create Event", new_event_path, class: "nav-link" %>
          <% if signed_in? %>
            <%= link_to "Your profile", current_user, class: "nav-link" %>
            <%= link_to "Sign out", destroy_user_session_path, class: "nav-link", method: "delete" %>
          <% else %>
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          <% end %>
        </nav>
        <% if signed_in? %>
          <%= render "users/invites_received", user: current_user %>
        <% end %>
      </aside>
      <main class="ms-4 mb-4">
        <div class="container-fluid">
          <%= yield %>
        </div>
      </main>
    </div>
  </body>
</html>

app/views/users/_invites_received.html.erb
<div class="invites-received mt-4">
    <h5 class="text-warning">Pending invites: </h5>
    <% if user.invites_received.empty? %>
        <p class="text-muted">Empty!</p>
    <% else %>
        <ul class="list-group">
            <% user.invites_received.each do |invite| %>
                <%= link_to invite.event, class: "text-decoration-none event-link" do %>
                    <li class="list-group-item miniature-event m-1">
                        <p class="text-muted">Event</p>
                        <h6 class="text-truncate"> <%= invite.event.name %></h6>
                    </li>
                <% end %>
            <% end %>
        </ul>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="profile-heading text-center">
    <h1>
        <% if @user == current_user %>
            Your (<%= @user.name %>) profile
        <% else %>
            <%= @user.name %>'s Profile
        <% end %>
    </h1>
        <div class="profile-menu">
            <% if @user == current_user %>
                <div class="edit-profile text-center">
                    <%= link_to "Edit Profile", edit_user_registration_path, class: "btn btn-primary" %>
                </div>
            <% end %>
            <% if @user.events.empty? && @user.attended_events.empty? %>
                <p class="text-muted m-2">User events will be displayed here.</p>
            <% else %>
                <a href="#created_events" class="btn btn-secondary m-1">Created events</a>
                <a href="#attended_events" class="btn btn-secondary m-1">Attended events</a>
            <% end %>
        </div>
</div>

<% unless @user.events.empty? && @user.attended_events.empty? %>
    <div class="user-events">
        <div class="created-events">
            <h1 class="mt-4 mb-0" id="created_events">Created Events</h1>
            <%= render "events/events", events: @user.events %>
        </div>
        <hr>
        <div class="attended-events">
            <h1 id="attended_events">Attended Events</h1>
            <%= render "events/events", events: @user.attended_events %>
        </div>
    </div>
<% end %>